apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: toharikrsample 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: toharikrsample 
    spec:
      containers:
        - name: toharikrsample 
          image: devopsazure66containerregistry.azurecr.io/toharikrsample
          ports:
          - containerPort: 8080